--liquibase formatted sql

--changeset CREATE_TABLE_PERSON:DDL:1
CREATE TABLE PERSON (
    ID UUID CONSTRAINT PK_PERSON PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DOCUMENT VARCHAR(21) NOT NULL,
    BIRTH_DATE TIMESTAMP NOT NULL
);

--changeset CREATE_TABLE_CONTACT:DDL:2
CREATE TABLE CONTACT (
    ID UUID CONSTRAINT PK_CONTACT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER NUMERIC NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PERSON_ID UUID NOT NULL,
    CONSTRAINT FK_CONTACT_PERSON FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID)
);

--changeset IDX_FK_CONTACT_PERSON:DDL:3
CREATE INDEX IDX_FK_CONTACT_PERSON
    ON CONTACT(PERSON_ID)